language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - coverage erase
  - coverage run --source=pythonproject -m unittest discover -v

after_success:
  - coveralls